### PR TITLE
Fetch release PR files to use in erb template

### PR DESCRIPTION
**Pull request by shibayu36**
This PR let us use information of changed files in the specified erb template.

I want to add checklists to release flow by changed files information.  For example, if `script/onetime/*` are updated, I want to add a checklist to exec these.  We can do it by the following code if changed files are passed to the erb template.

```
<%- if changed_files.any?{|f| f.filename.match(%r{^script/onetime/}) } -%>
- [ ] `script/onetime/*` are updated
<% changed_files.select{|f| f.filename.match(%r{^script/onetime/}) }.each do |file| %>
    - [ ] Exec `<%= file %>`
<% end %>
<%- end -%>
```

### CODE REVIEW

**Comment by shibayu36** [comment]
@motemen Please review it!

**Comment by motemen** [comment]
LGTM :smile:

**Comment by motemen** [comment]
Just released as [0.2.0](https://rubygems.org/gems/git-pr-release/versions/0.2.0).

**Comment by shibayu36** [comment]
Thanks!!!

**Pull request merged**
